repository: code4lib-japan/code4lib-japan.github.io
theme: jekyll-theme-cayman
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Dockerfile', 'docker-compose.yml']
baseurl: "https://code4lib-japan.github.io"