repository: code4lib-japan/code4lib-japan.github.io
#theme: jekyll-theme-cayman
theme: minima
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Dockerfile', 'docker-compose.yml']
permalink: /:year/:month/:slug
minima:
  date_format: "%Y年%m月%d日"