version: "3"
services:
  website:
    build: .
    tty: true
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    command: jekyll serve -d ./_site --watch --force_polling -H 0.0.0.0 -P 4000
